import streamlit as st

def get_bias_warning(language='PT-BR'):
    if language == 'EN':
        return """**⚠️ SAMPLE BIAS WARNING: INCOMPLETE PANORAMA (PARTIAL DATA)**

*Attention: The current selection does not cover all Civil Police careers.*

**What does this mean?**
By removing roles from the analysis, you stop observing the entire "statistical population" to observe only a "sample". This creates a **sample bias**.

**How does this affect the results?**
Distance algorithms (such as Gower) and network diagrams (Graphs and Trees) calculate a role's position by pushing and pulling it based on **all** the others. Without the complete panorama, the similarity between the remaining roles suffers distortions (a similarity might seem larger or smaller than it actually is in the complete ecosystem). This visualization is useful for specific focuses, but **does not represent the institution's global scenario.**"""

    return """**⚠️ AVISO DE VIÉS AMOSTRAL: PANORAMA INCOMPLETO (DADOS PARCIAIS)**

*Atenção: A seleção atual não contempla todas as carreiras da Polícia Civil.*

**O que isso significa?**
Ao remover cargos da análise, você deixa de observar a "população estatística" inteira para observar apenas uma "amostra". Isso gera um **viés amostral**.

**Como isso afeta os resultados?**
Os algoritmos de distância (como Gower) e os diagramas de rede (Grafos e Árvores) calculam a posição de um cargo empurrando e puxando-o com base em **todos** os outros. Sem o panorama completo, a similaridade entre os cargos remanescentes sofre distorções (uma similaridade pode parecer maior ou menor do que realmente é no ecossistema completo). Esta visualização é útil para focos específicos, mas **não representa o cenário global da instituição.**"""

def get_short_bias_warning(language='PT-BR'):
    if language == 'EN':
        return "**Sample Bias Reminder:** You disabled some roles from the analysis. The network and distance calculations displayed below reflect only the relationship of this sample, and not the real complete structure of the Police."
    return "**Lembrete de Viés Amostral:** Você desativou alguns cargos da análise. O cálculo de redes e distâncias exibido abaixo reflete apenas a relação desta amostra, e não a estrutura real completa da Polícia."

def get_explanation(section, tone="tecnico", language="PT-BR"):
    if language == "EN":
        explanations_en = {
            "tecnico": {
                "matriz": "**📖 Scientific Comprehension: Binary Assignments Matrix**\n\nThe Binary Matrix transforms textual data into rigorous numerical coordinates (0 or 1). \n- **Value 1:** Indicates the positive normative possession of the assignment by the role.\n- **Condensation Methodology:** The original study applied a dimensionality reduction filter. Identical assignments common to a fixed group of roles were merged into a single 'super-assignment'. This prevents noise generated by documents describing the same function in 10 different topics.",
                "adjacencia": "**📖 Scientific Comprehension: Adjacency Matrix**\n\nThe adjacency matrix measures co-occurrence.\n- **Calculation:** Dot Product of the binary matrix by its transpose.\n- **Interpretation:** Reveals absolute values. If the cell between Expert and Fingerprint Examiner shows '3', it means their matrices collide positively in exactly three normative sentences.",
                "explorador": "**📖 Scientific Comprehension: Dynamic Crosstab**\n\nExploratory tool that replicates the analytical model.\n- **Purpose:** Allows drill-down into sparse matrices to qualitatively inspect *which* variables constitute the intersection between roles.",
                "grafo": "**📖 Scientific Comprehension: Graph Diagram (NetworkX)**\n\nTopological network visualization of normative interactions.\n- **Applied Physics:** Uses the *Fruchterman-Reingold (Spring Layout)* algorithm.\n- **Interpretation:** Edges are adjacency connections. Roles with many common functions 'pull' each other to form dense clusters.",
                "gower": "**📖 Scientific Comprehension: Distance and Similarity Matrices (Errata)**\n\nMetrics calculate coefficients from 0.0 to 1.0. Values close to 1 represent total dissimilarity.\n- **Symmetric Metrics (e.g. Original Gower):** Count 'double zeros' (tasks neither role performs) as similarities, bringing roles closer for not having the same functions.\n- **Asymmetric Metrics (e.g. Jaccard):** Ignore 'double zeros', basing similarity strictly on active functions.\n- **🚨 Errata from the Published Article (RBCP):** The article text argues for asymmetric math (Jaccard). However, the published tables and charts reproduced the exact values of the **Symmetric Gower** distance. The application allows you to use 'Gower' to reproduce and audit the printed figures, or 'Jaccard' to apply the strict mathematical theory proposed in the text.",
                "regua": "**📖 Scientific Comprehension: Relative Distance Ruler**\n\nOne-dimensional projection of the Gower Coefficient focused on a 'zero point'.\n- **Interpretation:** Projects the Euclidean distance of the other roles from a fixed base.",
                "dendograma": "**📖 Scientific Comprehension: Hierarchical Tree (Dendrogram)**\n\nTaxonomic classification of careers based on the distance matrix.\n- **Algorithm:** Agglomerative Hierarchical Clustering.\n- **Linkage Methods:** 'Single' connects by the nearest neighbor (creates chains). 'Complete' connects by the furthest neighbor (creates tight spherical clusters). 'Average' connects by the mean distance of all points (robust middle-ground).",
                "upset": "**📖 Scientific Comprehension: Set Diagram (UpSet Plot)**\n\nAdvanced model for intersection visualization, superior to the classic Venn Diagram.\n- **Geometry:** Scans all matrix permutations and plots them as a barcode.",
                "m2_delta": "**📖 Scientific Comprehension: Gower Distance Delta**\n\nThe vector delta calculation measures the variation of a career's Gower distance at two different times.\n- **Interpretation:** A negative variation signals functional agglutination (roles became more similar/hybrid). A positive variation indicates that the roles isolated themselves functionally.",
                "m2_fluxo": "**📖 Scientific Comprehension: Normative Flow (Intersection Balance)**\n\nDemonstrates the exact fluctuation of binary coordinates (0 ➔ 1 or 1 ➔ 0).\n- **Interpretation:** Shows, without mathematical abstraction, exactly what a role was permitted to do and what was normatively suppressed, evidencing the scope of the structural mutation.",
                "m2_radar": "**📖 Scientific Comprehension: Affinity Metrics (Plane Geometry)**\n\nMeasures the intersection against the distinct functions. Can be customized:\n- **Jaccard:** Standard intersection/union proportion.\n- **Sokal & Sneath:** Double penalizes exclusive functions (mismatches).\n- **Dice / Gower 2:** Double weights shared functions (matches).\n- **Overlap:** Measures if one role is a strict subset of another.\n- **Cosine:** Geometric mean proportion.",
                "m2_grafo": "**📖 Scientific Comprehension: Topological Centrality Delta**\n\nCompares the density of connections (edges) in the two graph networks generated by adjacency.\n- **Interpretation:** A career that gains many new edges in the target scenario is assuming a central 'hub' position in the institution. If it loses edges, it is becoming an isolated node at the edge of the network.",
                "m2_dendro": "**📖 Scientific Comprehension: Phylogenetic Jump (Clades)**\n\nEvaluates whether vector distances altered the career's closest Euclidean neighbor.\n- **Interpretation:** A change of neighbor (branch in the tree) is the strongest indicator of a methodological rupture: it means the functional DNA of that role was so altered that it needed to be reclassified to another 'family' within the Police.",
                "m3_macro": "**📖 Scientific Comprehension: Global Analysis by Intersection Matrix**\n\nThe stacked visualization evidences secular trends in the Police matrices.\n- **Interpretation:** An increase in the 'Exclusive' block and a reduction in 'Shared' points to institutional specialization (segmentation). The reverse points to generalism and overlap of systemic competencies.",
                "m3_macro_31": "**📖 Scientific Comprehension: Total Volume per Scenario**\n\nDemonstrates the gross quantity of consolidated assignments in each temporal cut.\n- **Interpretation:** Verifies whether the regulations, in general, are expanding the functional scope of the Civil Police or shrinking the described assignments.",
                "m3_macro_32": "**📖 Scientific Comprehension: Exclusive vs Shared Proportion**\n\nEvaluates the percentage relationship between functions that belong to only one role and functions that belong to multiple roles.\n- **Interpretation:** A gain in exclusive assignments suggests greater specialization and isolation of careers. An increase in shared assignments indicates generalism and legal overlap.",
                "m3_macro_33": "**📖 Scientific Comprehension: Average Degree of Sharing**\n\nMeasures, on average, by how many different careers a normative assignment is divided.\n- **Interpretation:** High values demonstrate high capillarity of functions (generic assignments present in several regulations). Low values indicate that the assignments are well-niched.",
                "m4_micro": "**📖 Scientific Comprehension: Individual Evolutionary Tracking (Time Series)**\n\nDisaggregates global metrics and projects point variation across the 5 normative eras for isolated roles.\n- **Interpretation:** Analyzes the gain/loss of absolute functional volume (total), the fluctuation of magnetic distances, and the jumps of topological neighborhood. Serves to track the individualized historical genealogy.",
                "m4_micro_inicio": "**📖 Scientific Comprehension: Individual Evolutionary Tracking**\n\nDisaggregates global metrics and projects point variation across the 5 normative eras for isolated roles.\n- **Interpretation:** Analyzes the career variation in absolute volume, adjacency connections, Gower proximity, and phylogenetic jumps.",
                "m4_micro_41": "**📖 Scientific Comprehension: Functional Volume Fluctuation**\n\nTime series of the absolute count of active condensed assignments in the career profile.\n- **Interpretation:** Evidences growth (legal expansion of the role) or shrinkage (normative emptying).",
                "m4_micro_42": "**📖 Scientific Comprehension: Exclusivity Dynamics**\n\nTracks the internal proportion of exclusive (private) versus shared assignments.\n- **Interpretation:** Reveals whether the career is losing the monopoly of its functions (increase in shared) or gaining private niches.",
                "m4_micro_43": "**📖 Scientific Comprehension: Adjacency Density**\n\nSum of raw intersections with all other careers (Σ adjacencies).\n- **Interpretation:** Indicates how 'mixed' the career is. Peaks signal a sudden increase in common functions with other roles.",
                "m4_micro_44": "**📖 Scientific Comprehension: Degree Centrality**\n\nThe number of incident edges to the role's node in the connectivity mesh (threshold > 1).\n- **Interpretation:** Measures connection power (hub). Growth suggests the career interacts with more distinct careers than before.",
                "m4_micro_45": "**📖 Scientific Comprehension: Gower Distancing (Isolation)**\n\nArithmetic mean of Gower distances relative to the other nodes.\n- **Interpretation:** A decreasing vector means the role is becoming statistically more generic/similar to the rest of the corporation.",
                "m4_micro_46": "**📖 Scientific Comprehension: Neighborhood Rupture**\n\nTracks changes in the identity of the closest Euclidean neighbor (lowest Gower distance).\n- **Interpretation:** Changing neighbors represents a phylogenetic jump (Clade), signaling a radical change in the career's functional DNA."
            },
            "leigo": {
                "matriz": "**💡 Simplified Explanation: The Check-list Matrix**\n\nImagine we grabbed all the laws and made a huge check-list. If the role's law says it does a task, we mark '1' (Colored Box). If not, '0' (Empty). To avoid duplicate tasks confusing the system, we grouped identical tasks together.",
                "adjacencia": "**💡 Simplified Explanation: Adjacency (The Scoreboard)**\n\nThis is a scoreboard of coincidences. If you see the number '5' between two careers, it means they share exactly 5 identical tasks in their laws.",
                "explorador": "**💡 Simplified Explanation: The Explorer**\n\nHere you can open the 'hood' of the mathematics. Instead of just seeing that two roles share 10 tasks, you can filter and read exactly what those 10 tasks are.",
                "grafo": "**💡 Simplified Explanation: The Constellation (Graph)**\n\nThink of this as a solar system. Roles that share many tasks have a strong gravity and pull together into a cluster. Roles with unique tasks are pushed away to the edges.",
                "gower": "**💡 Simplified Explanation: Similarity Maps (Errata)**\n\nUnlike the scoreboard that only counts what they have in common, these metrics penalize what is different.\n- **Errata from the Published Article:** The article's text argues for the **Jaccard** metric (which ignores tasks that neither role performs). However, the values and charts printed in the article were calculated by the algorithm as **Gower** (which considers that 'not performing a task' is also a similarity). By selecting 'Gower (Used in the Article)' you see exactly what was published. By selecting 'Jaccard' you see the intended theory applied strictly.",
                "regua": "**💡 Simplified Explanation: The Ruler**\n\nIt places your chosen career at the zero mark of a ruler, and lines up all the others. The further to the right a career appears, the less it has in common with your chosen career.",
                "dendograma": "**💡 Simplified Explanation: The Family Tree**\n\nReads like an evolutionary tree. If two roles branch off from the same tip, they are functionally 'siblings'. If they separate at the root, they are 'distant cousins'.",
                "upset": "**💡 Simplified Explanation: The Combinations (UpSet)**\n\nInstead of messy overlapping circles (Venn), this chart creates a 'barcode' of combinations. Look at the dots below: if 3 roles have a dot, the bar above them shows exactly how many exclusive tasks that trio shares.",
                "m2_delta": "**💡 Simplified Explanation: Affinity Variation Map**\n\nThis board compares the distance ruler before and after.\n- **How to read:** Blue zones show where two roles became more similar over time. Red zones show they moved apart and nowadays perform more different tasks from each other.",
                "m2_fluxo": "**💡 Simplified Explanation: What Changed (Bank Statement)**\n\nIt is the literal statement of gains and losses.\n- **How to read:** No heavy math or charts. Clearly lists 'what the role could do before and can no longer do' (Losses) and 'what the role didn't do and started doing' (Gains).",
                "m2_radar": "**💡 Simplified Explanation: Functional Friendship Radar**\n\nMeasures what percentage of total tasks your role shares with its neighbor.\n- **How to read:** If the area (the drawn polygon) increased from one year to the next, it means the career started acting in various areas of other careers. If the area shrank, it closed itself in its own 'square'.",
                "m2_grafo": "**💡 Simplified Explanation: Change in the Web (Graph)**\n\nCompares how the 'spider web' changed.\n- **How to read:** If a role gained many links in the second web, it became a wildcard (hub) capable of performing tasks of several others. If it lost links, its work was segregated.",
                "m2_dendro": "**💡 Simplified Explanation: Branch Jump (Family Tree)**\n\nMeasures who the role's 'twin brother' is and if it changed families.\n- **How to read:** Analyze if the closest neighbor changed. If it changed (Branch Jump), it means the changes in the law were so drastic that the role that was most similar to you yesterday is no longer the same today.",
                "m3_macro": "**💡 Simplified Explanation: The Big Picture of the Police**\n\nLooking from above (without separating by role), how did the assignments evolve?\n- **How to read:** An increase in the red color (Exclusive) shows that professions are more separated and 'owners' of their tasks. An increase in the blue (Shared) shows a police where 'everyone does everything'.",
                "m3_macro_31": "**💡 Simplified Explanation: Total Growth**\n\nSums up everything the Police does in each era.\n- **How to read:** Went up? The Police has more rules about what to do. Went down? They shrank the assignments in the regulations.",
                "m3_macro_32": "**💡 Simplified Explanation: Exclusive vs Shared**\n\nCompares what belongs to only one profession with what 'everyone does'.\n- **How to read:** More red color (exclusive) means everyone is more in their own square. More blue (shared) means the careers are acting in the same areas.",
                "m3_macro_33": "**💡 Simplified Explanation: Average Sharing**\n\nOn average, by how many people is a task divided?\n- **How to read:** If the average goes up, tasks are increasingly diluted among several roles. If it goes down, functions are more specific to each profession.",
                "m4_micro": "**💡 Simplified Explanation: Individual History (Role X-Ray)**\n\nIt's like the role's vaccination card or school report card over time.\n- **How to read:** You follow the same line across all 5 scenarios. You can clearly see if, over the decades, the role gained workload (went up) or lost (went down), and if it got closer or further from other professions.",
                "m4_micro_inicio": "**💡 Simplified Explanation: The Role's X-Ray over Time**\n\nIt is the history of how the career changed from the first regulation to today.\n- **How to read:** Follow your career's line and see if, over the years, it gained or lost strength, and if it is getting more similar or different from the others.",
                "m4_micro_41": "**💡 Simplified Explanation: Total Functions**\n\nThe basic count of 'how many things' the role does.\n- **How to read:** Line going up means the role gained new responsibilities in the law. Line going down means emptying.",
                "m4_micro_42": "**💡 Simplified Explanation: Privilege vs Division**\n\nOf the things the role does, how many are ONLY theirs?\n- **How to read:** If the exclusive bar decreases over the years, it means the role lost exclusivities and started dividing the work with others.",
                "m4_micro_43": "**💡 Simplified Explanation: Degree of Mixture**\n\nMeasures how many tasks in total the role shares with the corporation.\n- **How to read:** Growth indicates that the career is increasingly juxtaposed and mixed with others' work.",
                "m4_micro_44": "**💡 Simplified Explanation: Connection Bridges**\n\nOut of 14 roles, with how many does your role have functions in common?\n- **How to read:** If before it shared tasks with 2 roles and now shares with 8, it became a 'wildcard' that acts throughout the precinct.",
                "m4_micro_45": "**💡 Simplified Explanation: Profession Isolation**\n\nHow 'unique' is your role compared to all others?\n- **How to read:** Line going up (near 1.0) means the career is distancing itself from everyone and becoming an island (isolated). Line going down means it is becoming a generic 'do-it-all'.",
                "m4_micro_46": "**💡 Simplified Explanation: Swap of 'Twin Brother'**\n\nWho is the role most similar to yours?\n- **How to read:** If the neighbor changes from one decade to another, the changes in the law were so heavy that you literally changed professional family."
            }
        }
        return explanations_en.get(tone, explanations_en["tecnico"]).get(section, "")
        
    explanations = {
        "tecnico": {
            "matriz": """**📖 Compreensão Científica: Matriz Binária de Atribuições**

A Matriz Binária transforma dados textuais (atribuições em editais e leis) em coordenadas numéricas rigorosas (0 ou 1). 
- **Valor 1 (Célula Colorida):** Indica a posse normativa positiva da atribuição pelo cargo.
- **Metodologia de Condensação:** O estudo original aplicou um filtro redutor de dimensionalidade. Atribuições idênticas comuns a um grupo fixo de cargos foram aglutinadas em uma única "super-atribuição" (coluna única). Isso previne distorções (ruído estatístico) geradas por documentos que descrevem a mesma função em 10 tópicos diferentes, o que criaria um peso artificial de similaridade na matemática do modelo.""",
            
            "adjacencia": """**📖 Compreensão Científica: Matriz de Adjacência**

A matriz de adjacência mede a coocorrência (frequência absoluta de interseções).
- **Cálculo:** Obtida por meio do Produto Escalar da matriz binária de atribuições por sua matriz transposta.
- **Interpretação:** Revela valores absolutos. Se a célula entre Perito e Papiloscopista exibe o valor "3", significa que, matematicamente, suas matrizes de atribuição colidem positivamente (ambos possuem o valor 1) em exatamente três orações normativas analisadas.""",
            
            "explorador": """**📖 Compreensão Científica: Cruzamento Dinâmico (Tabelas Dinâmicas)**

Ferramenta exploratória que replica e expande o modelo analítico adotado no artigo original.
- **Finalidade:** Permite o "drill-down" nas matrizes esparsas. Em vez de observar coeficientes de distância, o usuário inspeciona qualitativamente *quais* variáveis (atribuições) específicas constituem a intersecção entre conjuntos de cargos e calcula o "peso normativo" absoluto e percentual de cada carreira no ecossistema global.""",
            
            "grafo": """**📖 Compreensão Científica: Diagrama de Grafos (NetworkX)**

Visualização topológica de rede das interações normativas.
- **Física Aplicada:** Utiliza o algoritmo *Fruchterman-Reingold (Spring Layout)*.
- **Interpretação:** As arestas (linhas) são conexões de adjacência (compartilhamento de funções). O algoritmo simula repulsão e atração magnética. Cargos com muitas funções em comum "puxam-se" mutuamente para formar aglomerados (clusters) densos no centro ou extremidades da rede. Nós (cargos) sem conexões com a malha principal são repelidos para as bordas (dissimilaridade total).""",
            
            "gower": """**📖 Compreensão Científica: Matrizes de Distância e Similaridade (Errata)**
            
As métricas calculam coeficientes de 0.0 a 1.0 (ou 0% a 100%). Valores próximos a 1 na distância representam dissimilaridade total.
- **Métricas Simétricas (Ex: Gower Original):** Contabilizam os "zeros duplos" (tarefas que ambos não fazem) como semelhanças, aproximando cargos por não possuírem as mesmas funções.
- **Métricas Assimétricas (Ex: Jaccard):** Ignoram os "zeros duplos", baseando a similaridade estritamente nas funções ativas.
- **🚨 Errata do Artigo Publicado (RBCP):** O texto do artigo defende a matemática assimétrica (Jaccard) para não "aproximar artificialmente os cargos". Contudo, as tabelas, mapas de calor e réguas publicadas nas páginas da revista reproduziram os valores exatos da distância **Simétrica de Gower** (onde a biblioteca computou as igualdades negativas como similaridades, como o valor 0.71 para Perito x Papiloscopista). A aplicação permite que você utilize a opção "Gower" para reproduzir e auditar as figuras do artigo impresso, ou "Jaccard" para aplicar a rigorosa teoria matemática proposta no texto da obra.""",
            
            "regua": """**📖 Compreensão Científica: Régua de Distanciamento Relativo**

Projeção unidimensional do Coeficiente de Gower focada em um "ponto zero".
- **Interpretação:** Ao fixar uma carreira como base (marco 0.0), a régua projeta a distância euclidiana das demais. Serve para diagnosticar o desvio padrão funcional de todo o órgão em relação a um cargo de interesse (ex: "A que distância os demais estão do Perito Criminal?").""",
            
            "dendograma": """**📖 Compreensão Científica: Árvore Hierárquica (Dendograma)**

Classificação taxionômica das carreiras baseada na matriz de distâncias.
- **Algoritmo:** Clusterização Hierárquica Aglomerativa.
- **Métodos de Agrupamento (Linkage):** 'Single' aproxima pelo vizinho mais próximo (tende a criar correntes alongadas). 'Complete' aproxima pelo vizinho mais distante (força clusters coesos e fechados). 'Average' aproxima pela média das distâncias (meio-termo robusto).
- **Interpretação:** O eixo X mede o nível de especialização/distância. A árvore (clados) dicotomiza os cargos da base para a ponta. Ramos que se separam logo no início (à esquerda) indicam matrizes basais/generalistas comuns a muitos. Ramos que se agrupam apenas lá na ponta (à direita) representam altíssima proximidade funcional especializada.""",
            
            "upset": """**📖 Compreensão Científica: Diagrama de Conjuntos (UpSet Plot)**

Modelo avançado para visualização de interseções em múltiplos conjuntos, superior ao Diagrama de Venn clássico.
- **Geometria dos Conjuntos:** Matematicamente, círculos de Venn só suportam interseções exatas de no máximo 4 grupos antes de violarem a topologia espacial. O UpSet Plot resolve isso analisando todas as dezenas de permutações matriciais e plotando-as como um código de barras. A coluna preta demonstra o montante exato de atribuições que são de posse exclusiva daquela configuração exata de cargos assinalada na matriz inferior.""",
            
            "m2_delta": """**📖 Compreensão Científica: Delta de Distância de Gower**

O cálculo de delta vetorial mede a variação da distância de Gower de um cargo em dois tempos distintos.
- **Interpretação:** Uma variação negativa sinaliza aglutinação funcional (cargos tornaram-se mais similares/híbridos). Uma variação positiva indica que os cargos se isolaram funcionalmente.""",
            
            "m2_fluxo": """**📖 Compreensão Científica: Fluxo Normativo (Balanço de Interseções)**

Demonstra a flutuação exata das coordenadas binárias (0 ➔ 1 ou 1 ➔ 0).
- **Interpretação:** Exibe, sem abstração matemática, o que exatamente um cargo passou a ter permissão de fazer e o que lhe foi suprimido normativamente, evidenciando o escopo da mutação estrutural.""",
            
            "m2_radar": """**📖 Compreensão Científica: Métricas de Afinidade (Geometria Plana)**

O índice mede a intersecção contra as particularidades de dois conjuntos.
- **Métricas Personalizáveis:**
  - **Jaccard:** Proporção clássica (Intersecção / União).
  - **Sokal & Sneath:** Penaliza duplamente funções exclusivas de um cargo.
  - **Dice / Gower 2:** Bonifica duplamente as funções compartilhadas.
  - **Overlap:** Mede se um cargo é quase um subconjunto de funções do outro.
  - **Cosine:** Média geométrica de compartilhamento.""",
            
            "m2_grafo": """**📖 Compreensão Científica: Delta de Centralidade Topológica**

Compara a densidade de conexões (arestas) nas duas malhas de grafos geradas pela adjacência.
- **Interpretação:** Uma carreira que ganha muitas novas arestas no cenário alvo está assumindo uma posição de "hub" central na instituição. Se perde arestas, ela está se tornando um nó isolado na borda da rede.""",
            
            "m2_dendro": """**📖 Compreensão Científica: Salto Filogenético (Clados)**

Avalia se as distâncias vetoriais alteraram o vizinho euclidiano mais próximo da carreira.
- **Interpretação:** Uma mudança de vizinho (ramo na árvore) é o indicador mais forte de uma ruptura metodológica: significa que o DNA funcional daquele cargo foi tão alterado que ele precisou ser reclassificado para outra "família" dentro da Polícia.""",
            
            "m3_macro": """**📖 Compreensão Científica: Análise Global por Matriz de Interseções**

A visualização empilhada evidencia tendências seculares nas matrizes da Polícia.
- **Interpretação:** Um aumento no bloco de "Exclusivas" e redução nas "Compartilhadas" aponta para uma especialização institucional (segmentação). O inverso aponta para generalismo e sobreposição de competências sistêmicas.""",

            "m3_macro_31": """**📖 Compreensão Científica: Volume Total por Cenário**
    
Demonstra o quantitativo bruto de atribuições consolidadas em cada corte temporal.
- **Interpretação:** Verifica se as normativas, de modo geral, estão ampliando o escopo funcional da Polícia Civil ou enxugando as atribuições descritas.""",
            
            "m3_macro_32": """**📖 Compreensão Científica: Proporção Exclusiva vs Compartilhada**

Avalia a relação percentual entre funções que pertencem a apenas um cargo e funções que pertencem a múltiplos cargos.
- **Interpretação:** Um ganho em atribuições exclusivas sugere uma especialização maior e isolamento de carreiras. Um aumento de compartilhadas indica generalismo e sobreposição legal.""",
            
            "m3_macro_33": """**📖 Compreensão Científica: Grau Médio de Compartilhamento**

Mede, em média, por quantas carreiras distintas uma atribuição normativa é dividida.
- **Interpretação:** Valores altos demonstram alta capilaridade das funções (atribuições genéricas presentes em vários editais). Valores baixos indicam que as atribuições estão bem nichadas.""",
            
            "m4_micro": """**📖 Compreensão Científica: Rastreamento Evolutivo Individual (Séries Temporais)**

Desagrega as métricas globais e projeta a variação pontual ao longo das 5 eras normativas para os cargos isolados.
- **Interpretação:** Analisa o ganho/perda de volume funcional absoluto (total), a flutuação de distâncias magnéticas e os saltos de vizinhança topológica. Serve para rastrear a genealogia histórica individualizada.""",

            "m4_micro_inicio": """**📖 Compreensão Científica: Rastreamento Evolutivo Individual**
            
Desagrega as métricas globais e projeta a variação pontual ao longo das 5 eras normativas para os cargos isolados.
- **Interpretação:** Analisa a variação da carreira em volume absoluto, conexões de adjacência, proximidade de Gower e saltos filogenéticos.""",

            "m4_micro_41": """**📖 Compreensão Científica: Flutuação de Volume Funcional**
            
Série temporal da contagem absoluta de atribuições condensadas ativas no perfil da carreira.
- **Interpretação:** Evidencia crescimento (expansão legal do cargo) ou encolhimento (esvaziamento normativo).""",

            "m4_micro_42": """**📖 Compreensão Científica: Dinâmica de Exclusividade**
            
Acompanha a proporção interna de atribuições exclusivas (privativas) versus compartilhadas.
- **Interpretação:** Revela se a carreira está perdendo o monopólio de suas funções (aumento de compartilhadas) ou ganhando nichos privativos.""",

            "m4_micro_43": """**📖 Compreensão Científica: Densidade de Adjacência**
            
Soma das interseções brutas com todas as outras carreiras (Σ adjacências).
- **Interpretação:** Indica o quão "misturada" a carreira está. Picos sinalizam um aumento brusco de funções em comum com outros cargos.""",

            "m4_micro_44": """**📖 Compreensão Científica: Centralidade de Grau (Degree)**
            
O número de arestas incidentes ao nó do cargo na malha de conectividade (limiar > 1).
- **Interpretação:** Mede o poder de conexão (hub). Crescimento sugere que a carreira interage com mais carreiras distintas do que antes.""",

            "m4_micro_45": """**📖 Compreensão Científica: Distanciamento Gower (Isolamento)**
            
Média aritmética das distâncias de Gower em relação aos demais nós.
- **Interpretação:** Um vetor decrescente significa que o cargo está ficando estatisticamente mais genérico/parecido com o resto da corporação.""",

            "m4_micro_46": """**📖 Compreensão Científica: Ruptura de Vizinhança**
            
Rastreia alterações na identidade do vizinho euclidiano mais próximo (menor distância Gower).
- **Interpretação:** Troca de vizinho representa um salto filogenético (Clado), sinalizando mudança radical no DNA funcional da carreira."""
        },
        "leigo": {
            "matriz": """**🗣️ Entendendo de forma simples: A Tabela de Presença**

Pense nesta matriz como a folha de presença da escola ou escala de plantão.
- Se o quadrado tem cor (valor 1), a lei ou o edital diz que aquele cargo TEM que fazer aquela tarefa.
- Se estiver vazio (valor 0), o cargo NÃO faz.
- **O detalhe inteligente:** Se três cargos fazem exatamente a mesma coisa burocrática, o sistema conta isso como apenas *uma* tarefa, para não dar a falsa impressão de que eles fazem muitas coisas, quando na verdade é só a mesma tarefa repetida em várias linhas da lei.""",
            
            "adjacencia": """**🗣️ Entendendo de forma simples: Tabela de "Amizade" de Tarefas**

Essa tabela conta, em números absolutos, quantas tarefas dois cargos têm em comum.
- **Como ler:** Cruze a linha de um cargo com a coluna do outro. Se estiver marcado "3", significa que eles compartilham exatamente três obrigações legais. Cores escuras indicam cargos que dividem muitas tarefas.""",
            
            "explorador": """**🗣️ Entendendo de forma simples: O Explorador de Dados**

Aqui você pode investigar com uma lupa o que está por trás dos números.
- Você pode selecionar cargos e ver uma lista em português claro de **quais** tarefas eles têm em comum, ou quais são exclusivas de um único profissional. É ótimo para responder à pergunta: 'Afinal, quem na Polícia tem autorização legal para fazer o procedimento X?'""",
            
            "grafo": """**🗣️ Entendendo de forma simples: A "Teia de Aranha" das Funções**

Este gráfico cria um modelo físico onde os cargos são como ímãs.
- **Como ler:** As linhas que conectam as "bolas" (cargos) representam tarefas divididas. Quanto mais funções em comum, mais forte é a atração magnética. Por isso, cargos parecidos terminam sendo "puxados" para formar um bolinho juntos, enquanto cargos muito diferentes ficam soltos e isolados nas pontas.""",
            
            "gower": """**🗣️ Entendendo de forma simples: Mapas de Distância (Errata)**

Diferente da tabela de amizade (que só vê o que é igual), estas métricas descontam e medem diferenças.
- **Errata do Artigo Publicado:** O texto do artigo original afirma que utilizou Jaccard (que ignora tarefas que ambos não fazem). Porém, os gráficos e tabelas impressos na revista foram calculados pelo algoritmo como Gower (que considera que não fazer uma tarefa também é uma similaridade). Escolha "Gower" para ver exatamente o que foi publicado, ou "Jaccard" para aplicar a teoria rigorosa da obra.""",
            
            "regua": """**🗣️ Entendendo de forma simples: A Régua de Distância**

Imagine que você coloque o seu cargo escolhido na marca "Zero" de uma fita métrica.
- Este gráfico mostra a que distância todos os outros cargos estão de você. Cargos colados perto do Zero fazem um trabalho muito parecido com o seu. Cargos lá no final da régua (perto de 1.0) fazem um trabalho completamente diferente.""",
            
            "dendograma": """**🗣️ Entendendo de forma simples: A Árvore Genealógica das Carreiras**

Este gráfico tenta agrupar a Polícia em "famílias" com base na proximidade do trabalho.
- **Como ler:** Acompanhe as linhas da direita para a esquerda. Se dois cargos se juntam muito cedo numa "garfo" da árvore (bem à direita), eles são como gêmeos. Se a linha deles viaja muito para a esquerda antes de encontrar alguém, eles fazem um trabalho bem exclusivo e isolado do resto.""",
            
            "upset": """**💬 Entendendo de forma simples: O Gráfico de Fatias Exclusivas**

Sabe aquele antigo desenho de dois círculos se cruzando (Diagrama de Venn)? Na Polícia, com 14 cargos, é impossível desenhar aquilo no papel. Este gráfico resolve o problema.
- **Como ler:** Olhe para o nome do grupo (eixo X) ou passe o mouse sobre a barra. Isso mostra "quem" está no grupo. A barra alta (eixo Y) mostra **quantas tarefas** pertencem exclusivamente e unicamente àquele grupo de carreiras. É excelente para ver quais grupos "monopolizam" certos trabalhos na Polícia.""",

            "m2_delta": """**🗣️ Entendendo de forma simples: Mapa de Variação de Afinidade**

Este quadro compara a régua de distância antes e depois.
- **Como ler:** Zonas azuis mostram onde dois cargos ficaram mais parecidos com o tempo. Zonas vermelhas mostram que eles se afastaram e hoje em dia realizam tarefas mais diferentes um do outro.""",
            
            "m2_fluxo": """**🗣️ Entendendo de forma simples: O Que Mudou (Extrato da Conta)**

É o extrato literal de ganhos e perdas.
- **Como ler:** Sem gráficos ou matemática pesada. Lista claramente "o que o cargo podia fazer antes e não pode mais" (Perdas) e "o que o cargo não fazia e passou a fazer" (Ganhos).""",
            
            "m2_radar": """**🗣️ Entendendo de forma simples: Radar de Amizade Funcional**

Mede qual porcentagem das tarefas totais o seu cargo divide com o vizinho.
- **Como ler:** Se a área (o polígono desenhado) aumentou de um ano para o outro, significa que a carreira passou a atuar em várias áreas de outras carreiras. Se a área encolheu, ela se fechou no próprio "quadrado".""",
            
            "m2_grafo": """**🗣️ Entendendo de forma simples: Mudança na Malha (Grafo)**

Compara como a "teia de aranha" mudou.
- **Como ler:** Se um cargo ganhou muitos elos (links) na segunda teia, ele virou um curinga (hub) capaz de realizar tarefas de vários outros. Se perdeu elos, seu trabalho foi segregado.""",
            
            "m2_dendro": """**🗣️ Entendendo de forma simples: Salto de Galho (Árvore Genealógica)**

Mede quem é o "irmão gêmeo" do cargo e se ele trocou de família.
- **Como ler:** Analise se o vizinho mais próximo mudou. Se mudou (Salto de Ramo), quer dizer que as mudanças na lei foram tão drásticas que o cargo que era mais parecido com você ontem não é mais o mesmo de hoje.""",
            
            "m3_macro": """**🗣️ Entendendo de forma simples: A Fotografia Geral da Polícia**

Olhando de cima (sem separar por cargo), como as atribuições evoluíram?
- **Como ler:** Aumento na cor vermelha (Exclusivas) mostra que as profissões estão mais separadas e "donas" de suas tarefas. Aumento na azul (Compartilhadas) mostra uma polícia onde "todo mundo faz tudo".""",

            "m3_macro_31": """**🗣️ Entendendo de forma simples: Crescimento Total**
            
Soma tudo o que a Polícia faz em cada época.
- **Como ler:** Subiu? A Polícia tem mais regras sobre o que fazer. Desceu? Enxugaram as atribuições nos editais.""",

            "m3_macro_32": """**🗣️ Entendendo de forma simples: Exclusivas vs Compartilhadas**

Compara o que é de uma profissão só com o que "todo mundo faz".
- **Como ler:** Mais cor vermelha (exclusivas) significa que cada um está mais no seu quadrado. Mais azul (compartilhadas) significa que as carreiras estão atuando nas mesmas áreas.""",

            "m3_macro_33": """**🗣️ Entendendo de forma simples: Média de Compartilhamento**

Em média, por quantas pessoas uma tarefa é dividida?
- **Como ler:** Se a média sobe, as tarefas estão cada vez mais diluídas entre vários cargos. Se desce, as funções estão mais específicas para cada profissão.""",
            
            "m4_micro": """**🗣️ Entendendo de forma simples: Histórico Individual (Raio-X do Cargo)**

É como a carteirinha de vacinação ou o boletim escolar do cargo ao longo do tempo.
- **Como ler:** Você acompanha a mesma linha em todos os 5 cenários. Pode ver claramente se, ao longo das décadas, o cargo ganhou volume de trabalho (subiu) ou perdeu (desceu), e se ele se aproximou ou se afastou das outras profissões.""",

            "m4_micro_inicio": """**🗣️ Entendendo de forma simples: O Raio-X do Cargo no Tempo**

É o histórico de como a carreira mudou desde o primeiro edital até hoje.
- **Como ler:** Acompanhe a linha do seu cargo e veja se, com o passar dos anos, ele foi ganhando ou perdendo força, e se está ficando mais parecido ou diferente dos outros.""",

            "m4_micro_41": """**🗣️ Entendendo de forma simples: Total de Funções**

A contagem básica de "quantas coisas" o cargo faz.
- **Como ler:** Linha subindo significa que o cargo ganhou novas responsabilidades na lei. Linha caindo significa esvaziamento.""",

            "m4_micro_42": """**🗣️ Entendendo de forma simples: Privilégio vs Divisão**

Das coisas que o cargo faz, quantas são SÓ dele?
- **Como ler:** Se a barra de exclusivas diminui ao longo dos anos, significa que o cargo perdeu exclusividades e passou a dividir o trabalho com outros.""",

            "m4_micro_43": """**🗣️ Entendendo de forma simples: Grau de Mistura**

Mede quantas tarefas no total o cargo divide com a corporação.
- **Como ler:** Crescimento indica que a carreira está cada vez mais justaposta e misturada com o trabalho alheio.""",

            "m4_micro_44": """**🗣️ Entendendo de forma simples: Pontes de Conexão**

De 14 cargos, com quantos o seu cargo tem funções em comum?
- **Como ler:** Se antes ele dividia tarefas com 2 cargos e agora divide com 8, ele virou um "coringa" que atua em toda a delegacia.""",

            "m4_micro_45": """**🗣️ Entendendo de forma simples: Isolamento da Profissão**

O quão "único" é o seu cargo comparado a todos os outros?
- **Como ler:** Linha subindo (perto de 1.0) significa que a carreira está se distanciando de todos e virando uma ilha (isolada). Linha descendo significa que está virando um "faz tudo" genérico.""",

            "m4_micro_46": """**🗣️ Entendendo de forma simples: Troca de "Irmão Gêmeo"**

Quem é o cargo mais parecido com o seu?
- **Como ler:** Se o vizinho muda de uma década para outra, as alterações na lei foram tão pesadas que você literalmente mudou de família profissional."""
        }
    }
    
    # Validação e fallback
    t = tone.lower()
    if "leigo" in t or "simplificado" in t:
        t = "leigo"
    else:
        t = "tecnico"
        
    return explanations.get(t, explanations["tecnico"]).get(section, "")
